openapi: 3.0.2
info:
  title: Games-API
  version: 1.0.0
  description: |-
    ### This is a Swagger UI for our Games API


    ### Error handling
    Errors are presented using the HTTP status codes 400-599. The response include a more detailed explanation about the error in the body.

    ```
    {
      "error": "Cleartext explanation of the error that occurred"
    }
    ```

    ### Generic API errors
    These error responses can be returned by any of the described endpoints.

    | HTTP status  |  Description |
    |---|---|
    | 400| Bad input parameters or invalid request. More information can be found in the response body.
    | 401| The consumer does not have access to the requested resource or the provided token is not valid.
    | 404| The requested resource can not be found or the user does not have access to the resource.
    | 5XX| A server error has occurred while processing the request.
paths:
  /games:
    get:
      tags:
        - games
      summary: Get a list of all games
      description: Returns a list of all games in API
      responses:
        '200':
          description: Returns a list of games
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                List of games:
                  value:
                    - Cizzbor
                    - Woowo
                    - Crazlinger
    post:
      tags:
        - new-game
      summary: Creates a game
      description: Creates a new game
      requestBody:
        description: A new game to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-game'
      responses:
        '201':
          description: Game was created. The Location header points to the new game.
          headers:
            Location:
              description: URL of the created game
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'
              examples:
                Created game:
                  value:
                    id: 6
                    name: Tetris
                    price: 0.99
        '400':
          description: One or all params are missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                Missing params:
                  value:
                    error: One or all params are missing
                Invalid price:
                  value:
                    error: Price must be a number that is 0 or greater
  /games/{id}:
    parameters:
      - name: id
        in: path
        description: Id of the game
        required: true
        schema:
          type: integer
    get:
      tags:
        - details
      summary: Get full details of a game
      description: Returns full details of a given id game
      responses:
        '200':
          description: Returns full details of a given id game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'
              examples:
                Full details of a given game:
                  value:
                    id: 1
                    name: Cizzbor
                    price: 29.99
        '400':
          description: Game id is not a positive integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                Invalid id:
                  value:
                    error: Game id must be a positive integer
        '404':
          description: Game was not found in games array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                Game was not found:
                  value:
                    error: Game not found
    delete:
      tags:
        - delete-game
      summary: Deletes a game
      description: Deletes a game with the given id
      responses:
        '204':
          description: Game was deleted
        '400':
          description: Game id is not a positive integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                Invalid id:
                  value:
                    error: Game id must be a positive integer
        '404':
          description: Game was not found in games array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                Game was not found:
                  value:
                    error: Game not found
components:
  schemas:
    error:
      title: Root Type for error
      type: object
      properties:
        error:
          type: string
      example:
        error: Error message.
    game:
      title: Root Type for game
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          format: float
          type: number
      example:
        id: 1
        name: Cizzbor
        price: 29.99
    new-game:
      title: Root Type for new-game
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
        price:
          format: float
          type: number
      example:
        name: Tetris
        price: 0.99
    delete-game:
      title: Root Type for delete-game
      type: object
      required:
        - id
      properties:
        id:
          type: integer
      example:
        id: 1
